catalog.http.port: 8080
connection_string: mongodb://catalog-mongodb:27017
db_name: catalogdb
username: mongo
password: mongo

service-name: catalog-service
reporter-log-spans: True
sampler-type: ratelimiting
sampler-param: 1